{{- $root := . -}}
{{- range $name, $comp := ( .Values.components | default dict ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slar.componentFullname" (dict "root" $root "name" $name) }}
  labels:
    {{- include "slar.componentLabels" (dict "root" $root "name" $name) | nindent 4 }}
spec:
  {{- if not $root.Values.autoscaling.enabled }}
  replicas: {{ default $root.Values.replicaCount $comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slar.componentSelectorLabels" (dict "root" $root "name" $name) | nindent 6 }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slar.componentLabels" (dict "root" $root "name" $name) | nindent 8 }}
        {{- with $root.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slar.serviceAccountName" $root }}
      {{- with $root.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          {{- with $root.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $comp.image.repository }}:{{ $comp.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ default $root.Values.image.pullPolicy $comp.image.pullPolicy | default "IfNotPresent" }}
          {{- if and $comp.service $comp.service.port }}
          ports:
            - name: http
              containerPort: {{ $comp.service.port }}
              protocol: TCP
          {{- end }}
          {{- with $comp.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $comp.resources }}
          resources:
            {{- toYaml $comp.resources | nindent 12 }}
          {{- else if $root.Values.resources }}
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          {{- end }}
          {{- with $root.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $root.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
