{{- $root := . -}}
{{- range $name, $comp := ( .Values.components | default dict ) }}
{{- if and $comp.service $comp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slar.componentFullname" (dict "root" $root "name" $name) }}
  labels:
    {{- include "slar.componentLabels" (dict "root" $root "name" $name) | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $comp.service.type }}
  ports:
    - port: {{ $comp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "slar.componentSelectorLabels" (dict "root" $root "name" $name) | nindent 4 }}
---
{{- end }}
{{- end }}
